# Ruff configuration file for version 0.1.9
# Enable comprehensive linting rules
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "YTT", # flake8-2020
    "S",   # flake8-bandit (security)
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "C4",  # flake8-comprehensions
    "T20", # flake8-print
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "Q",   # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "TCH", # flake8-type-checking
]

# Ignore specific rules that might be too strict for this project
ignore = [
    "S101",  # Use of assert
    "T201",  # Print found (allow print statements)
    "B008",  # Do not perform function calls in argument defaults
    "S603",  # subprocess call: check for execution of untrusted input
    "S607",  # Starting a process with a partial executable path
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "chroma_db",
    "*.ipynb",  # Exclude Jupyter notebooks
]

# Align with pyproject.toml settings
line-length = 135
target-version = "py311"

[flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"

[isort]
known-first-party = ["document_processor", "rag_engine", "llm_tools"]
split-on-trailing-comma = true
